import type { CardThemeDef } from '../types'

export const magazineMinimal: CardThemeDef = {
  id: 'magazine-minimal',
  label: '杂志极简',
  group: 'magazine',
  desc: '大留白 · 资讯报道风',
  style: {
    h1Style: 'default',
    h2Style: 'border-left',
    headerDecor: 'thin-line',
    codeBordered: true,
    bgPattern: 'color-block',
    coverLayout: 'magazine',
    blockquoteStyle: 'bar',
  },
  tokens: {
    contentBg: '#ffffff',
    exportBg: '#ffffff',
    coverBg: '#ffffff',
    ink: '#111111',
    inkSoft: '#555555',
    accent: '#111111',
    accentWeak: 'rgba(17,17,17,0.08)',
    link: '#111111',
    codeBg: '#f5f5f5',
    preBg: '#f5f5f5',
    hr: '#e0e0e0',
    tableBorder: '#e0e0e0',
    tableHeadBg: '#fafafa',
    footerDash: '#e0e0e0',
    brandColor: '#111111',
    pageColor: '#999999',
    headingFont: '"Helvetica Neue",Helvetica,Arial,sans-serif',
    bodyFont: '"Helvetica Neue",Helvetica,Arial,sans-serif',
    contentPadX: 22,
    contentPadY: 20,
  },
}
