import type { CardThemeDef } from '../types'

export const monoCode: CardThemeDef = {
  id: 'mono-code',
  label: '极客暗黑',
  group: 'dark',
  desc: 'GitHub 暗色 · 技术文档 / 代码笔记',
  style: {
    h1Style: 'accent-bar',
    h2Style: 'accent-underline',
    headerDecor: 'accent-strip',
    codeBordered: true,
    bgPattern: 'tech-grid',
    coverLayout: 'big-title',
    blockquoteStyle: 'highlight',
  },
  tokens: {
    contentBg: '#161b22',
    exportBg: '#161b22',
    ink: '#e6edf3',
    inkSoft: '#8b949e',
    accent: '#58a6ff',
    accentWeak: 'rgba(88,166,255,0.2)',
    link: '#58a6ff',
    codeBg: '#0d1117',
    preBg: '#0d1117',
    hr: '#30363d',
    tableBorder: '#30363d',
    tableHeadBg: '#0d1117',
    footerDash: '#30363d',
    brandColor: '#58a6ff',
    pageColor: '#6e7681',
    accentBar: '#58a6ff',
    bodyFont: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif',
    headingFont: 'ui-sans-serif, system-ui, -apple-system, "Segoe UI", "PingFang SC", sans-serif',
    blockquoteBg: 'rgba(88,166,255,0.08)',
    contentPadX: 22,
    contentPadY: 20,
  },
}
