import type { DraftThemeId } from '@/engine/themes/markdownThemes/drafts/generated'
import { hexAlpha } from '../../cardThemePatterns'
import type { CardThemeDef, CardThemeGroup, CardThemeStyleFlags, CardThemeTokens } from '../types'

const SERIF = 'Georgia, "Songti SC", "STSong", "Source Han Serif SC", serif'

interface TokenInput {
  contentBg: string
  ink: string
  inkSoft: string
  accent: string
  hr?: string
  codeBg?: string
  headingFont?: string
  bodyFont?: string
  blockquoteBg?: string
}

function baseTokens(input: TokenInput): CardThemeTokens {
  const { contentBg, ink, inkSoft, accent } = input
  const hr = input.hr ?? hexAlpha(ink, 0.22)
  const codeBg = input.codeBg ?? hexAlpha(ink, 0.06)
  return {
    contentBg,
    exportBg: contentBg,
    coverBg: contentBg,
    ink,
    inkSoft,
    accent,
    accentWeak: hexAlpha(accent, 0.15),
    link: accent,
    codeBg,
    preBg: codeBg,
    hr,
    tableBorder: hr,
    tableHeadBg: hexAlpha(accent, 0.08),
    footerDash: hr,
    brandColor: accent,
    pageColor: inkSoft,
    accentBar: accent,
    headingFont: input.headingFont,
    bodyFont: input.bodyFont,
    blockquoteBg: input.blockquoteBg ?? hexAlpha(accent, 0.08),
    contentPadX: 20,
    contentPadY: 18,
  }
}

function theme(
  id: DraftThemeId,
  label: string,
  group: CardThemeGroup,
  desc: string,
  tokens: CardThemeTokens,
  style: CardThemeStyleFlags,
): CardThemeDef {
  return { id, label, group, desc, tokens, style }
}

const scrapbookStyle: CardThemeStyleFlags = {
  h1Style: 'highlight-marker',
  h2Style: 'pill',
  headerDecor: 'none',
  codeBordered: true,
  bgPattern: 'fine-grid',
  coverLayout: 'sticker',
  blockquoteStyle: 'rounded',
  hrStyle: 'stripes',
  strongStyle: 'highlight',
  linkUnderline: 'wavy',
  bqShadowOffset: 3,
  h1Rotate: -0.5,
  preStyle: 'card',
  tableRadius: 12,
}

const cuteStyle: CardThemeStyleFlags = {
  h1Style: 'highlight-marker',
  h2Style: 'pill-solid',
  headerDecor: 'none',
  codeBordered: true,
  bgPattern: 'bloom',
  coverLayout: 'sticker',
  blockquoteStyle: 'rounded',
  hrStyle: 'text',
  strongStyle: 'highlight',
  linkUnderline: 'wavy',
  bqShadowOffset: 4,
  h3Style: 'emoji',
  showHeadingDecor: true,
  liMarker: '🍡 ',
  tableRadius: 16,
}

/** 与公众号排版草案主题同源的 19 套知识卡片主题 */
export const WECHAT_DRAFT_CARD_THEMES: CardThemeDef[] = [
  theme(
    'zhuYinSeal',
    '朱砂印谱',
    'culture',
    '米宣纸底 + 朱印点缀 + 宋体居中引文',
    baseTokens({
      contentBg: '#FBF6EE',
      ink: '#3A322C',
      inkSoft: '#5C534C',
      accent: '#8B1E1E',
      hr: '#C9A86C',
      headingFont: SERIF,
      bodyFont: SERIF,
      blockquoteBg: hexAlpha('#8B1E1E', 0.06),
    }),
    {
      h1Style: 'center-line',
      h2Style: 'border-left',
      headerDecor: 'gradient-fade',
      codeBordered: true,
      bgPattern: 'paper-grain',
      coverLayout: 'classic',
      blockquoteStyle: 'literary',
    },
  ),
  theme(
    'deepLetter',
    '深海信笺',
    'culture',
    '深夜蓝底 + 金线分隔 + 衬线长文',
    baseTokens({
      contentBg: '#0F172A',
      ink: '#CBD5E1',
      inkSoft: '#94A3B8',
      accent: '#C9A961',
      hr: hexAlpha('#C9A961', 0.35),
      codeBg: '#1E293B',
      headingFont: SERIF,
      bodyFont: SERIF,
      blockquoteBg: hexAlpha('#C9A961', 0.08),
    }),
    {
      h1Style: 'serif-elegant',
      h2Style: 'accent-underline',
      headerDecor: 'thin-line',
      codeBordered: true,
      bgPattern: 'film-grain',
      coverLayout: 'magazine',
      blockquoteStyle: 'bar',
    },
  ),
  theme(
    'mintScrapbook',
    '薄荷手帐',
    'scrapbook',
    '手账纸纹 + 和纸胶带标题 + 圆角卡片引文',
    baseTokens({
      contentBg: '#FAFFFC',
      ink: '#065F46',
      inkSoft: '#475569',
      accent: '#7ECBA1',
      hr: '#A7F3D0',
    }),
    scrapbookStyle,
  ),
  theme(
    'peachScrapbook',
    '蜜桃手帐',
    'scrapbook',
    '暖橙奶黄胶带 + 网格纸底',
    baseTokens({
      contentBg: '#FFFBF7',
      ink: '#44403C',
      inkSoft: '#57534E',
      accent: '#FDBA74',
      hr: '#FFE8D6',
    }),
    scrapbookStyle,
  ),
  theme(
    'lavenderScrapbook',
    '薰衣草手帐',
    'scrapbook',
    '淡紫网格 + 粉紫胶带',
    baseTokens({
      contentBg: '#FDFCFF',
      ink: '#5B21B6',
      inkSoft: '#4B5563',
      accent: '#A78BFA',
      hr: '#EDE9FE',
      blockquoteBg: '#F5F3FF',
    }),
    scrapbookStyle,
  ),
  theme(
    'skyScrapbook',
    '晴空手帐',
    'scrapbook',
    '天蓝柠檬双拼胶带',
    baseTokens({
      contentBg: '#FAFCFF',
      ink: '#1E40AF',
      inkSoft: '#475569',
      accent: '#93C5FD',
      hr: '#DBEAFE',
    }),
    scrapbookStyle,
  ),
  theme(
    'softRound',
    '圆润物语',
    'modern',
    '左色条标题 + 细描边胶囊 + 轻阴影卡片',
    baseTokens({
      contentBg: '#F9FAFC',
      ink: '#2A3142',
      inkSoft: '#6B7590',
      accent: '#5B6CFE',
      hr: hexAlpha('#5B6CFE', 0.2),
    }),
    {
      h1Style: 'accent-bar',
      h2Style: 'pill',
      headerDecor: 'accent-strip',
      codeBordered: true,
      bgPattern: 'soft-wash',
      coverLayout: 'split-block',
      blockquoteStyle: 'rounded',
    },
  ),
  theme(
    'freshBreeze',
    '清风浅蓝',
    'modern',
    '天蓝 + 薄荷白底 + 通透间距',
    baseTokens({
      contentBg: '#F0FDFA',
      ink: '#0F766E',
      inkSoft: '#475569',
      accent: '#38BDF8',
      hr: hexAlpha('#38BDF8', 0.25),
    }),
    {
      h1Style: 'accent-bar',
      h2Style: 'pill',
      headerDecor: 'thin-line',
      codeBordered: true,
      bgPattern: 'bloom',
      coverLayout: 'classic',
      blockquoteStyle: 'bar',
    },
  ),
  theme(
    'techGrid',
    '极客蓝图',
    'modern',
    '网格底纹 + 等宽点缀 + 蓝色信息块',
    baseTokens({
      contentBg: '#FFFFFF',
      ink: '#0F172A',
      inkSoft: '#334155',
      accent: '#0EA5E9',
      hr: hexAlpha('#0EA5E9', 0.2),
      codeBg: '#F1F5F9',
      bodyFont: 'ui-monospace, "JetBrains Mono", Consolas, monospace',
    }),
    {
      h1Style: 'accent-bar',
      h2Style: 'bracket-square',
      headerDecor: 'accent-strip',
      codeBordered: true,
      bgPattern: 'tech-grid',
      coverLayout: 'big-title',
      blockquoteStyle: 'highlight',
    },
  ),
  theme(
    'formalGraphite',
    '石墨简报',
    'formal',
    '黑白极简 + 左色条分节',
    baseTokens({
      contentBg: '#FFFFFF',
      ink: '#171717',
      inkSoft: '#525252',
      accent: '#171717',
      hr: '#E5E5E5',
    }),
    {
      h1Style: 'accent-bar',
      h2Style: 'border-left',
      headerDecor: 'thin-line',
      codeBordered: true,
      bgPattern: 'none',
      coverLayout: 'classic',
      blockquoteStyle: 'bar',
    },
  ),
  theme(
    'formalNavy',
    '藏青纪事',
    'formal',
    '深藏青标题块 + 权威感',
    baseTokens({
      contentBg: '#FFFFFF',
      ink: '#1E3A5F',
      inkSoft: '#475569',
      accent: '#1E3A5F',
      hr: hexAlpha('#1E3A5F', 0.15),
      blockquoteBg: hexAlpha('#1E3A5F', 0.06),
    }),
    {
      h1Style: 'default',
      h2Style: 'border-left',
      headerDecor: 'accent-strip',
      codeBordered: true,
      bgPattern: 'soft-wash',
      coverLayout: 'classic',
      blockquoteStyle: 'bar',
    },
  ),
  theme(
    'formalEditorial',
    '专栏纪述',
    'formal',
    '衬线居中 + 报刊分节',
    baseTokens({
      contentBg: '#FAFAF9',
      ink: '#1C1917',
      inkSoft: '#57534E',
      accent: '#78716C',
      hr: '#E7E5E4',
      headingFont: SERIF,
      bodyFont: SERIF,
    }),
    {
      h1Style: 'serif-elegant',
      h2Style: 'accent-underline',
      headerDecor: 'thin-line',
      codeBordered: true,
      bgPattern: 'paper-grain',
      coverLayout: 'journal',
      blockquoteStyle: 'literary',
    },
  ),
  theme(
    'cuteBubble',
    '软萌泡泡',
    'cute',
    '马卡龙粉 + 气泡标题 + emoji 角标',
    baseTokens({
      contentBg: '#FFFBFC',
      ink: '#BE185D',
      inkSoft: '#6B5A62',
      accent: '#FF8FAB',
      hr: '#FFC8DD',
    }),
    { ...cuteStyle, bgPattern: 'macaron-dots' },
  ),
  theme(
    'cuteMilkTea',
    '奶茶波波',
    'cute',
    '奶咖焦糖 + 立体胶囊 + 贴纸引文',
    baseTokens({
      contentBg: '#FFFCF8',
      ink: '#A16207',
      inkSoft: '#6B5A4F',
      accent: '#D4A574',
      hr: '#ECD9C8',
    }),
    cuteStyle,
  ),
  theme(
    'cuteStarDream',
    '星梦软糖',
    'cute',
    '紫蓝梦境 + 星月角标',
    baseTokens({
      contentBg: '#FDFCFF',
      ink: '#6D28D9',
      inkSoft: '#5E5878',
      accent: '#A78BFA',
      hr: '#C4B5FD',
    }),
    cuteStyle,
  ),
  theme(
    'cuteLemonFizz',
    '柠檬汽水',
    'cute',
    '黄绿撞色 + 气泡感',
    baseTokens({
      contentBg: '#FFFEF5',
      ink: '#A16207',
      inkSoft: '#6B6538',
      accent: '#FACC15',
      hr: '#FDE68A',
    }),
    cuteStyle,
  ),
  theme(
    'cuteMatchaCloud',
    '抹茶云朵',
    'cute',
    '抹茶绿 + 奶黄双拼',
    baseTokens({
      contentBg: '#FAFFFC',
      ink: '#047857',
      inkSoft: '#4D6358',
      accent: '#6EE7B7',
      hr: '#BBF7D0',
    }),
    cuteStyle,
  ),
  theme(
    'cuteBlueberryJelly',
    '蓝莓果冻',
    'cute',
    '靛蓝冰透 + 果冻质感',
    baseTokens({
      contentBg: '#FAFBFF',
      ink: '#4338CA',
      inkSoft: '#505578',
      accent: '#818CF8',
      hr: '#C7D2FE',
    }),
    cuteStyle,
  ),
  theme(
    'cuteShuitunLulu',
    '水豚噜噜',
    'cute',
    '芒果暖黄 + 头顶小橙，佛系治愈',
    baseTokens({
      contentBg: '#FFFDF8',
      ink: '#B45309',
      inkSoft: '#786048',
      accent: '#FBBF24',
      hr: '#FCD88A',
    }),
    cuteStyle,
  ),
]
