import type { CardThemeDef } from '../types'

/** Canva 小红书精选 */
export const xhsPalmEditorial: CardThemeDef = {
  id: 'xhs-palm-editorial',
  label: '棕榈极简',
  group: 'xhs',
  desc: '沙色底 · 叶影 · 白卡片',
  style: {
    shellLayout: 'xhs-palm-editorial',
    coverLayout: 'xhs-palm-editorial',
    headerDecor: 'none',
    h1Style: 'serif-elegant',
    h2Style: 'accent-underline',
    bgPattern: 'none',
    blockquoteStyle: 'bar',
  },
  tokens: {
    contentBg: 'linear-gradient(165deg,#b8956c 0%,#d4b896 45%,#e8d4bc 100%)',
    exportBg: '#d4b896',
    coverBg: 'linear-gradient(165deg,#b8956c 0%,#d4b896 45%,#e8d4bc 100%)',
    innerCardBg: 'rgba(255,255,255,0.92)',
    ink: '#5c4033',
    inkSoft: '#8b7355',
    accent: '#a67c52',
    accentWeak: 'rgba(166,124,82,0.2)',
    link: '#7c5c3c',
    codeBg: 'rgba(92,64,51,0.08)',
    preBg: '#f5ebe0',
    hr: '#d4b896',
    tableBorder: '#e8d4bc',
    tableHeadBg: '#f5ebe0',
    footerDash: '#c9a87c',
    brandColor: '#7c5c3c',
    pageColor: '#a08b76',
    headingFont: `Georgia,'Noto Serif SC',serif`,
    bodyFont: `'PingFang SC','Microsoft YaHei',sans-serif`,
    frameBorder: '#c9a87c',
    contentPadX: 16,
    contentPadY: 18,
  },
}

/** Canva 小红书精选 · 详情内页 4 款 */
export const xhsWorkplace: CardThemeDef = {
  id: 'xhs-workplace',
  label: '职场详情',
  group: 'xhs',
  desc: '青蓝渐变 · 喇叭 · 编号列表',
  style: {
    shellLayout: 'xhs-workplace',
    coverLayout: 'xhs-workplace',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'pill',
    bgPattern: 'soft-wash',
    blockquoteStyle: 'bar',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: 'linear-gradient(180deg,#b8e4f5 0%,#e8f6fc 55%,#ffffff 100%)',
    exportBg: '#e8f6fc',
    coverBg: 'linear-gradient(180deg,#b8e4f5 0%,#e8f6fc 55%,#ffffff 100%)',
    ink: '#1a1a1a',
    inkSoft: '#4a5568',
    accent: '#3b8fd9',
    accentWeak: 'rgba(59,143,217,0.18)',
    link: '#1d4ed8',
    codeBg: 'rgba(59,143,217,0.1)',
    preBg: '#e8f4fc',
    hr: '#b8e4f5',
    tableBorder: '#bfdbfe',
    tableHeadBg: '#e8f4fc',
    footerDash: '#93c5fd',
    brandColor: '#1d4ed8',
    pageColor: '#64748b',
    frameBorder: '#7ec8e3',
    chipBg: 'rgba(184,228,245,0.6)',
    chipBorder: '#93c5fd',
    chipInk: '#1e40af',
    contentPadX: 16,
    contentPadY: 14,
  },
}

export const xhsMedia: CardThemeDef = {
  id: 'xhs-media',
  label: '自媒体详情',
  group: 'xhs',
  desc: '紫底 · 白卡片 · 编号模块',
  style: {
    shellLayout: 'xhs-media',
    coverLayout: 'xhs-media',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'numbered-box',
    bgPattern: 'bloom',
    blockquoteStyle: 'rounded',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: 'linear-gradient(160deg,#c4b5fd 0%,#ddd6fe 40%,#ede9fe 75%,#f5f3ff 100%)',
    exportBg: '#ede9fe',
    coverBg: 'linear-gradient(160deg,#c4b5fd 0%,#ddd6fe 40%,#ede9fe 75%,#f5f3ff 100%)',
    innerCardBg: '#ffffff',
    ink: '#1e3a5f',
    inkSoft: '#4c1d95',
    accent: '#7c3aed',
    accentWeak: 'rgba(124,58,237,0.15)',
    link: '#6d28d9',
    codeBg: 'rgba(124,58,237,0.1)',
    preBg: '#f5f3ff',
    hr: '#ddd6fe',
    tableBorder: '#e9d5ff',
    tableHeadBg: '#f5f3ff',
    footerDash: '#c4b5fd',
    brandColor: '#6d28d9',
    pageColor: '#8b5cf6',
    contentPadX: 14,
    contentPadY: 14,
  },
}

export const xhsMemphis: CardThemeDef = {
  id: 'xhs-memphis',
  label: '孟菲斯详情',
  group: 'xhs',
  desc: '黄框 · 粗体标题 · STEP 标签',
  style: {
    shellLayout: 'xhs-memphis',
    coverLayout: 'xhs-memphis',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'step-tag',
    bgPattern: 'color-block',
    blockquoteStyle: 'highlight',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: '#f5d020',
    exportBg: '#faf7f2',
    coverBg: '#7cb87a',
    innerCardBg: '#faf7f2',
    ink: '#1a1a1a',
    inkSoft: '#374151',
    accent: '#4ade80',
    accentWeak: 'rgba(74,222,128,0.25)',
    link: '#15803d',
    codeBg: 'rgba(74,222,128,0.15)',
    preBg: '#ecfdf5',
    hr: '#d1d5db',
    tableBorder: '#e5e7eb',
    tableHeadBg: '#f3f4f6',
    footerDash: '#fbbf24',
    brandColor: '#15803d',
    pageColor: '#6b7280',
    frameBorder: '#1a1a1a',
    contentPadX: 14,
    contentPadY: 14,
  },
}

export const xhsScrapbook: CardThemeDef = {
  id: 'xhs-scrapbook',
  label: '手账详情',
  group: 'xhs',
  desc: '薄荷框 · 网格纸 · 笔刷标题',
  style: {
    shellLayout: 'xhs-scrapbook',
    coverLayout: 'xhs-scrapbook',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'pill',
    bgPattern: 'fine-grid',
    blockquoteStyle: 'rounded',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: '#a8dcc0',
    exportBg: '#ffffff',
    coverBg: '#a8dcc0',
    innerCardBg: '#ffffff',
    ink: '#166534',
    inkSoft: '#15803d',
    accent: '#86efac',
    accentWeak: 'rgba(134,239,172,0.35)',
    link: '#16a34a',
    codeBg: 'rgba(22,163,74,0.1)',
    preBg: '#ecfdf5',
    hr: '#bbf7d0',
    tableBorder: '#d1fae5',
    tableHeadBg: '#ecfdf5',
    footerDash: '#86efac',
    brandColor: '#16a34a',
    pageColor: '#4ade80',
    contentPadX: 14,
    contentPadY: 14,
  },
}

/** Canva 小红书精选 · 扩展 4 款 */
export const xhsFashionClass: CardThemeDef = {
  id: 'xhs-fashion-class',
  label: '时装周课堂',
  group: 'xhs',
  desc: '深棕底 · 时尚插画 · 胶囊标签',
  style: {
    shellLayout: 'xhs-fashion-class',
    coverLayout: 'xhs-fashion-class',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'pill',
    bgPattern: 'none',
    blockquoteStyle: 'literary',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: 'linear-gradient(165deg,#3d2b1f 0%,#5c4033 55%,#4a3428 100%)',
    exportBg: '#4a3428',
    coverBg: 'linear-gradient(165deg,#3d2b1f 0%,#5c4033 55%,#4a3428 100%)',
    ink: '#fef3e2',
    inkSoft: '#e8d4bc',
    accent: '#f5d020',
    accentWeak: 'rgba(245,208,32,0.2)',
    link: '#fcd34d',
    codeBg: 'rgba(245,208,32,0.12)',
    preBg: 'rgba(255,255,255,0.08)',
    hr: 'rgba(255,255,255,0.15)',
    tableBorder: 'rgba(255,255,255,0.12)',
    tableHeadBg: 'rgba(255,255,255,0.06)',
    footerDash: 'rgba(255,255,255,0.2)',
    brandColor: '#fcd34d',
    pageColor: '#d4b896',
    chipBg: 'rgba(245,208,32,0.25)',
    chipBorder: 'rgba(245,208,32,0.4)',
    chipInk: '#fef3e2',
    contentPadX: 14,
    contentPadY: 14,
  },
}

export const xhsJobChecklist: CardThemeDef = {
  id: 'xhs-job-checklist',
  label: '求职课堂',
  group: 'xhs',
  desc: '明黄底 · 活页清单 · 勾选列表',
  style: {
    shellLayout: 'xhs-job-checklist',
    coverLayout: 'xhs-job-checklist',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'accent-underline',
    bgPattern: 'fine-grid',
    blockquoteStyle: 'bar',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: '#fef08a',
    exportBg: '#fef08a',
    coverBg: '#fef08a',
    innerCardBg: '#ffffff',
    ink: '#1a1a1a',
    inkSoft: '#4b5563',
    accent: '#f97316',
    accentWeak: 'rgba(249,115,22,0.18)',
    link: '#ea580c',
    codeBg: 'rgba(249,115,22,0.1)',
    preBg: '#fff7ed',
    hr: '#fde68a',
    tableBorder: '#fcd34d',
    tableHeadBg: '#fef9c3',
    footerDash: '#fbbf24',
    brandColor: '#ea580c',
    pageColor: '#78716c',
    contentPadX: 14,
    contentPadY: 16,
  },
}

export const xhsPhotoNotes: CardThemeDef = {
  id: 'xhs-photo-notes',
  label: '摄影入门',
  group: 'xhs',
  desc: '浅蓝底 · 活页环 · 参数标签',
  style: {
    shellLayout: 'xhs-photo-notes',
    coverLayout: 'xhs-photo-notes',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'bracket-square',
    bgPattern: 'wave-ground',
    blockquoteStyle: 'bar',
    olAccentNumbers: true,
    codeBordered: true,
  },
  tokens: {
    contentBg: '#b8dff5',
    exportBg: '#b8dff5',
    coverBg: '#b8dff5',
    innerCardBg: '#ffffff',
    ink: '#1e40af',
    inkSoft: '#3b82f6',
    accent: '#2563eb',
    accentWeak: 'rgba(37,99,235,0.15)',
    link: '#1d4ed8',
    codeBg: 'rgba(37,99,235,0.1)',
    preBg: '#eff6ff',
    hr: '#93c5fd',
    tableBorder: '#bfdbfe',
    tableHeadBg: '#dbeafe',
    footerDash: '#60a5fa',
    brandColor: '#1d4ed8',
    pageColor: '#64748b',
    chipBg: 'rgba(184,223,245,0.6)',
    chipBorder: '#93c5fd',
    chipInk: '#1e40af',
    contentPadX: 14,
    contentPadY: 18,
  },
}

export const xhsOutdoorCopy: CardThemeDef = {
  id: 'xhs-outdoor-copy',
  label: '户外文案',
  group: 'xhs',
  desc: '鼠尾草绿 · 虚线框 · 编号清单',
  style: {
    shellLayout: 'xhs-outdoor-copy',
    coverLayout: 'xhs-outdoor-copy',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'numbered-box',
    bgPattern: 'dashed-frame',
    blockquoteStyle: 'rounded',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: '#e8f0e4',
    exportBg: '#e8f0e4',
    coverBg: '#e8f0e4',
    innerCardBg: 'rgba(255,255,255,0.85)',
    ink: '#2d4a2d',
    inkSoft: '#4a6b4a',
    accent: '#5c7a5c',
    accentWeak: 'rgba(92,122,92,0.2)',
    link: '#3d6b3d',
    codeBg: 'rgba(92,122,92,0.1)',
    preBg: '#f0f5ee',
    hr: '#a8c9a0',
    tableBorder: '#c5d9c0',
    tableHeadBg: '#f0f5ee',
    footerDash: '#a8c9a0',
    brandColor: '#3d6b3d',
    pageColor: '#6b8b6b',
    frameBorder: '#a8c9a0',
    chipBg: 'rgba(168,201,160,0.4)',
    chipBorder: '#a8c9a0',
    chipInk: '#2d4a2d',
    contentPadX: 14,
    contentPadY: 14,
  },
}

/** Canva 小红书精选 · 文艺 4 款 */
export const xhsVintageQuote: CardThemeDef = {
  id: 'xhs-vintage-quote',
  label: '小众情感语录',
  group: 'xhs',
  desc: '巧克力棕 · 撕纸卡片 · 玫瑰线稿',
  style: {
    shellLayout: 'xhs-vintage-quote',
    coverLayout: 'xhs-vintage-quote',
    headerDecor: 'none',
    h1Style: 'center-line',
    h2Style: 'accent-underline',
    bgPattern: 'none',
    blockquoteStyle: 'literary',
  },
  tokens: {
    contentBg: '#4a2c2a',
    exportBg: '#4a2c2a',
    coverBg: '#4a2c2a',
    innerCardBg: '#f5f0e6',
    ink: '#2d1810',
    inkSoft: '#5c4033',
    accent: '#c9a87c',
    accentWeak: 'rgba(201,168,124,0.2)',
    link: '#8b6914',
    codeBg: 'rgba(92,64,51,0.08)',
    preBg: '#ede8dc',
    hr: '#d4c4a8',
    tableBorder: '#e8dcc8',
    tableHeadBg: '#f5f0e6',
    footerDash: '#c9a87c',
    brandColor: '#8b6914',
    pageColor: '#a08b76',
    headingFont: `Georgia,'Noto Serif SC',serif`,
    bodyFont: `Georgia,'Noto Serif SC',serif`,
    contentPadX: 16,
    contentPadY: 16,
  },
}

export const xhsPoeticMist: CardThemeDef = {
  id: 'xhs-poetic-mist',
  label: '诗意惊蛰',
  group: 'xhs',
  desc: '灰米色 · 山雾剪影 · 双线框',
  style: {
    shellLayout: 'xhs-poetic-mist',
    coverLayout: 'xhs-poetic-mist',
    headerDecor: 'none',
    h1Style: 'default',
    h2Style: 'accent-underline',
    bgPattern: 'mountain-mist',
    blockquoteStyle: 'literary',
  },
  tokens: {
    contentBg: '#e8e4df',
    exportBg: '#e8e4df',
    coverBg: '#e8e4df',
    innerCardBg: 'rgba(255,255,255,0.75)',
    ink: '#3d3d3d',
    inkSoft: '#6b6b6b',
    accent: '#9ca3af',
    accentWeak: 'rgba(156,163,175,0.2)',
    link: '#6b7280',
    codeBg: 'rgba(107,114,128,0.1)',
    preBg: '#f3f4f6',
    hr: '#d1d5db',
    tableBorder: '#e5e7eb',
    tableHeadBg: '#f9fafb',
    footerDash: '#d1d5db',
    brandColor: '#6b7280',
    pageColor: '#9ca3af',
    frameBorder: '#9ca3af',
    headingFont: `'STKaiti','KaiTi',serif`,
    contentPadX: 16,
    contentPadY: 16,
  },
}

export const xhsSolarScience: CardThemeDef = {
  id: 'xhs-solar-science',
  label: '二十四节气',
  group: 'xhs',
  desc: '浅蓝渐变 · 青瓦 · 科普方框',
  style: {
    shellLayout: 'xhs-solar-science',
    coverLayout: 'xhs-solar-science',
    headerDecor: 'none',
    h1Style: 'center-line',
    h2Style: 'bracket-square',
    bgPattern: 'fine-grid',
    blockquoteStyle: 'rounded',
    olAccentNumbers: true,
  },
  tokens: {
    contentBg: 'linear-gradient(180deg,#e8f4fc 0%,#fff 100%)',
    exportBg: '#e8f4fc',
    coverBg: 'linear-gradient(180deg,#e8f4fc 0%,#fff 100%)',
    innerCardBg: 'rgba(255,255,255,0.95)',
    ink: '#1e4d5c',
    inkSoft: '#2d6a7a',
    accent: '#0d9488',
    accentWeak: 'rgba(13,148,136,0.15)',
    link: '#0f766e',
    codeBg: 'rgba(13,148,136,0.1)',
    preBg: '#f0fdfa',
    hr: '#99f6e4',
    tableBorder: '#ccfbf1',
    tableHeadBg: '#f0fdfa',
    footerDash: '#5eead4',
    brandColor: '#0f766e',
    pageColor: '#64748b',
    frameBorder: '#0d9488',
    headingFont: `'STKaiti','KaiTi',serif`,
    contentPadX: 14,
    contentPadY: 16,
  },
}

export const XHS_CANVA_THEMES: CardThemeDef[] = [
  xhsPalmEditorial,
  xhsWorkplace,
  xhsMedia,
  xhsMemphis,
  xhsScrapbook,
  xhsFashionClass,
  xhsJobChecklist,
  xhsPhotoNotes,
  xhsOutdoorCopy,
  xhsVintageQuote,
  xhsPoeticMist,
  xhsSolarScience,
]
