import { COVER_FONT_OPTIONS } from './constants'
import type { CoverTemplate, CoverTemplateGroup } from './types'

const FONT = {
  sans: COVER_FONT_OPTIONS[0].value,
  notoSans: COVER_FONT_OPTIONS[1].value,
  notoSerif: COVER_FONT_OPTIONS[2].value,
  wenkai: COVER_FONT_OPTIONS[3].value,
  mashan: COVER_FONT_OPTIONS[4].value,
} as const

/** 小红书笔记常用墨色（与 xhs/tokens 对齐） */
const XHS_INK = '#1F1A17'
const XHS_INK_SOFT = '#5C5346'

export const COVER_TEMPLATE_GROUPS: { key: CoverTemplateGroup; label: string }[] = [
  { key: 'xhs', label: '小红书' },
  { key: 'wechat', label: '微信公众号' },
  { key: 'business', label: '商务专业' },
  { key: 'literary', label: '文艺温暖' },
  { key: 'creative', label: '创意国风' },
  { key: 'minimal', label: '极简纸感' },
]

export const COVER_TEMPLATES: CoverTemplate[] = [
  {
    id: 'xhs-hit-title',
    label: '爆款大字',
    desc: '左上白字 · 竖版种草首图',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#fff1f2',
    layout: 'left',
    bgPresetId: 'xhs-coral',
    overlayOpacity: 0.1,
    aspect: 'portrait',
  },
  {
    id: 'xhs-cream-note',
    label: '奶油笔记',
    desc: '左上深字 · 干货清单风',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'left',
    bgPresetId: 'xhs-cream',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-coral-sweet',
    label: '甜系种草',
    desc: '居中 · 珊瑚粉氛围',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ffe4e6',
    layout: 'center',
    bgPresetId: 'xhs-coral',
    overlayOpacity: 0.14,
    aspect: 'portrait',
  },
  {
    id: 'xhs-macaron-diary',
    label: '手账日记',
    desc: '左上 · 马卡龙拼色',
    group: 'xhs',
    fontFamily: FONT.wenkai,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'left',
    bgPresetId: 'xhs-macaron',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-lavender-mood',
    label: '莫兰迪紫',
    desc: '居中 · 氛围感封面',
    group: 'xhs',
    fontFamily: FONT.notoSerif,
    titleColor: '#ffffff',
    keywordsColor: '#f3e8ff',
    layout: 'center',
    bgPresetId: 'xhs-lavender',
    overlayOpacity: 0.18,
    aspect: 'portrait',
  },
  {
    id: 'xhs-mint-life',
    label: '清新日常',
    desc: '左上 · 生活方式',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ecfdf5',
    layout: 'left',
    bgPresetId: 'xhs-mint',
    overlayOpacity: 0.16,
    aspect: 'portrait',
  },
  {
    id: 'xhs-warm-dry',
    label: '暖橙干货',
    desc: '左上 · 教程攻略风',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ffedd5',
    layout: 'left',
    bgPresetId: 'xhs-sunset',
    overlayOpacity: 0.12,
    aspect: 'portrait',
  },
  {
    id: 'xhs-serif-edit',
    label: '杂志编辑',
    desc: '居中 · 宋体高级感',
    group: 'xhs',
    fontFamily: FONT.notoSerif,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'center',
    bgPresetId: 'xhs-cream',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'wechat-classic',
    label: '经典横封',
    desc: '居中白字 · 2.35:1 标准',
    group: 'wechat',
    fontFamily: FONT.sans,
    titleColor: '#ffffff',
    keywordsColor: '#ecfdf5',
    layout: 'center',
    bgPresetId: 'wechat-green',
    overlayOpacity: 0.12,
    aspect: 'wechat',
  },
  {
    id: 'wechat-news',
    label: '资讯左对齐',
    desc: '左上 · 灰蓝专业感',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#e2e8f0',
    layout: 'left',
    bgPresetId: 'wechat-slate',
    overlayOpacity: 0.1,
    aspect: 'wechat',
  },
  {
    id: 'wechat-cinnabar-head',
    label: '头条朱砂',
    desc: '左上 · 热点深度文',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#fef3c7',
    layout: 'left',
    bgPresetId: 'wechat-cinnabar',
    overlayOpacity: 0.14,
    aspect: 'wechat',
  },
  {
    id: 'wechat-tech',
    label: '科技深空',
    desc: '左上 · 技术教程',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#cbd5e1',
    layout: 'left',
    bgPresetId: 'ink-night',
    overlayOpacity: 0.18,
    aspect: 'wechat',
  },
  {
    id: 'wechat-paper',
    label: '人文纸感',
    desc: '左上深字 · 文化随笔',
    group: 'wechat',
    fontFamily: FONT.notoSerif,
    titleColor: '#292524',
    keywordsColor: '#57534e',
    layout: 'left',
    bgPresetId: 'paper-warm',
    overlayOpacity: 0,
    aspect: 'wechat',
  },
  {
    id: 'wechat-minimal',
    label: '极简素雅',
    desc: '居中 · 浅色底深字',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#1e293b',
    keywordsColor: '#64748b',
    layout: 'center',
    bgPresetId: 'wechat-soft',
    overlayOpacity: 0,
    aspect: 'wechat',
  },
  {
    id: 'wechat-jade',
    label: '青玉国风',
    desc: '居中 · 传统文化',
    group: 'wechat',
    fontFamily: FONT.wenkai,
    titleColor: '#fef9c3',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'wechat-jade',
    overlayOpacity: 0.2,
    aspect: 'wechat',
  },
  {
    id: 'wechat-brush',
    label: '墨韵毛笔',
    desc: '居中 · 诗词散文',
    group: 'wechat',
    fontFamily: FONT.mashan,
    titleColor: '#fef3c7',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'wechat-ink',
    overlayOpacity: 0.22,
    aspect: 'wechat',
  },
  {
    id: 'wechat-misty',
    label: '雾蓝商务',
    desc: '左上 · 品牌专栏',
    group: 'wechat',
    fontFamily: FONT.sans,
    titleColor: '#ffffff',
    keywordsColor: '#f0f9ff',
    layout: 'left',
    bgPresetId: 'misty-blue',
    overlayOpacity: 0.12,
    aspect: 'wechat',
  },
  {
    id: 'wechat-forest',
    label: '森系自然',
    desc: '居中 · 环保健康',
    group: 'wechat',
    fontFamily: FONT.notoSerif,
    titleColor: '#ffffff',
    keywordsColor: '#d1fae5',
    layout: 'center',
    bgPresetId: 'forest-mist',
    overlayOpacity: 0.2,
    aspect: 'wechat',
  },
  {
    id: 'tech-dark',
    label: '科技深蓝',
    desc: '居中白字 · 适合技术分享',
    group: 'business',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#e2e8f0',
    layout: 'center',
    bgPresetId: 'ink-night',
    overlayOpacity: 0.2,
  },
  {
    id: 'misty-pro',
    label: '雾蓝商务',
    desc: '左上排版 · 清爽专业',
    group: 'business',
    fontFamily: FONT.sans,
    titleColor: '#ffffff',
    keywordsColor: '#f0f9ff',
    layout: 'left',
    bgPresetId: 'misty-blue',
    overlayOpacity: 0.15,
  },
  {
    id: 'forest-calm',
    label: '森系沉稳',
    desc: '居中 · 自然绿调',
    group: 'business',
    fontFamily: FONT.notoSerif,
    titleColor: '#ffffff',
    keywordsColor: '#d1fae5',
    layout: 'center',
    bgPresetId: 'forest-mist',
    overlayOpacity: 0.25,
  },
  {
    id: 'sunrise-warm',
    label: '晨光暖调',
    desc: '居中 · 生活随笔',
    group: 'literary',
    fontFamily: FONT.wenkai,
    titleColor: '#ffffff',
    keywordsColor: '#fff7ed',
    layout: 'center',
    bgPresetId: 'sunrise-glow',
    overlayOpacity: 0.18,
  },
  {
    id: 'paper-editorial',
    label: '纸感杂志',
    desc: '左上 · 深色字纸面',
    group: 'literary',
    fontFamily: FONT.notoSerif,
    titleColor: '#292524',
    keywordsColor: '#57534e',
    layout: 'left',
    bgPresetId: 'paper-warm',
    overlayOpacity: 0,
  },
  {
    id: 'ink-brush',
    label: '墨韵国风',
    desc: '居中毛笔 · 诗意封面',
    group: 'creative',
    fontFamily: FONT.mashan,
    titleColor: '#fef3c7',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'ink-night',
    overlayOpacity: 0.35,
  },
  {
    id: 'forest-poetry',
    label: '林间诗意',
    desc: '居中霞鹜 · 自然文艺',
    group: 'creative',
    fontFamily: FONT.wenkai,
    titleColor: '#ffffff',
    keywordsColor: '#ecfdf5',
    layout: 'center',
    bgPresetId: 'forest-mist',
    overlayOpacity: 0.3,
  },
  {
    id: 'sunrise-bold',
    label: '暖橙大字',
    desc: '左上 · 醒目标题',
    group: 'creative',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ffedd5',
    layout: 'left',
    bgPresetId: 'sunrise-glow',
    overlayOpacity: 0.22,
  },
  {
    id: 'minimal-paper',
    label: '极简留白',
    desc: '居中 · 纸面轻字',
    group: 'minimal',
    fontFamily: FONT.sans,
    titleColor: '#44403c',
    keywordsColor: '#78716c',
    layout: 'center',
    bgPresetId: 'paper-warm',
    overlayOpacity: 0,
  },
  {
    id: 'minimal-blue',
    label: '雾蓝轻简',
    desc: '居中 · 低遮罩清爽',
    group: 'minimal',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#f8fafc',
    layout: 'center',
    bgPresetId: 'misty-blue',
    overlayOpacity: 0.08,
  },
]

export function getCoverTemplate(id: string): CoverTemplate | undefined {
  return COVER_TEMPLATES.find((t) => t.id === id)
}

export function coverTemplateStyleFields(template: CoverTemplate) {
  return {
    fontFamily: template.fontFamily,
    titleColor: template.titleColor,
    keywordsColor: template.keywordsColor,
    layout: template.layout,
    bgPresetId: template.bgPresetId,
    overlayOpacity: template.overlayOpacity,
  }
}
