import { COVER_FONT_OPTIONS } from './constants'
import type { CoverAspect, CoverEditorState, CoverTemplate, CoverTemplateGroup } from './types'

const FONT = {
  sans: COVER_FONT_OPTIONS[0].value,
  notoSans: COVER_FONT_OPTIONS[1].value,
  notoSerif: COVER_FONT_OPTIONS[2].value,
  wenkai: COVER_FONT_OPTIONS[3].value,
  mashan: COVER_FONT_OPTIONS[4].value,
} as const

/** 小红书笔记常用墨色（与 xhs/tokens 对齐） */
const XHS_INK = '#1F1A17'
const XHS_INK_SOFT = '#5C5346'

export const COVER_TEMPLATE_GROUPS: { key: CoverTemplateGroup; label: string }[] = [
  { key: 'xhs', label: '小红书' },
  { key: 'wechat', label: '微信公众号' },
  { key: 'business', label: '商务专业' },
  { key: 'literary', label: '文艺温暖' },
  { key: 'creative', label: '创意国风' },
  { key: 'minimal', label: '极简纸感' },
]

export const COVER_TEMPLATES: CoverTemplate[] = [
  {
    id: 'xhs-canva-spring',
    label: '早春出游季',
    desc: '柠绿矢量 · 云朵相框封面',
    group: 'xhs',
    layoutPreset: 'xhs-spring-outing',
    fontFamily: FONT.notoSans,
    titleColor: '#1a1a1a',
    keywordsColor: '#1a1a1a',
    layout: 'left',
    bgPresetId: 'xhs-spring-lime',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 38,
    keywordsFontSize: 13,
    defaultTitle: '早春\n出游季',
    defaultKeywords: '立春* BEGINNING OF SPRING',
  },
  {
    id: 'xhs-canva-notebook',
    label: '笔记本干货',
    desc: '浅蓝手绘 · 荧光笔标题',
    group: 'xhs',
    layoutPreset: 'xhs-notebook-dry',
    fontFamily: FONT.notoSans,
    titleColor: '#1a1a1a',
    keywordsColor: '#ffffff',
    layout: 'left',
    bgPresetId: 'xhs-notebook-sky',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 34,
    keywordsFontSize: 14,
    defaultTitle: '超干货！！\n——新媒体运营',
    defaultKeywords: '建议收藏',
  },
  {
    id: 'xhs-canva-browser',
    label: '浏览器科普',
    desc: '波点蓝 · 窗口 CTA 按钮',
    group: 'xhs',
    layoutPreset: 'xhs-browser-cta',
    fontFamily: FONT.notoSans,
    titleColor: '#1a1a1a',
    keywordsColor: '#ffffff',
    layout: 'center',
    bgPresetId: 'xhs-polka-blue',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 32,
    keywordsFontSize: 15,
    defaultTitle: '肠胃健康\n这样来保障',
    defaultKeywords: '点进来学！',
  },
  {
    id: 'xhs-canva-palm',
    label: '棕榈极简',
    desc: '沙色叶影 · 品牌感封面',
    group: 'xhs',
    layoutPreset: 'xhs-palm-editorial',
    fontFamily: FONT.notoSerif,
    titleColor: '#92400e',
    keywordsColor: '#78716c',
    layout: 'center',
    bgPresetId: 'xhs-palm-sand',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 30,
    keywordsFontSize: 12,
    defaultTitle: '编辑你的\n标题',
    defaultKeywords: '请在此编辑主题或想法',
  },
  {
    id: 'xhs-canva-workplace',
    label: '职场新人',
    desc: '青蓝详情 · 编号清单体',
    group: 'xhs',
    layoutPreset: 'xhs-detail-workplace',
    fontFamily: FONT.notoSans,
    titleColor: '#1a1a1a',
    keywordsColor: '#374151',
    layout: 'left',
    bgPresetId: 'xhs-detail-cyan',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 34,
    keywordsFontSize: 14,
    defaultTitle: '职场新人必备',
    defaultKeywords: '——避免学生思维',
  },
  {
    id: 'xhs-canva-media',
    label: '自媒体清单',
    desc: '淡紫详情 · 卡片编号体',
    group: 'xhs',
    layoutPreset: 'xhs-detail-media',
    fontFamily: FONT.notoSans,
    titleColor: '#1e3a5f',
    keywordsColor: '#4c1d95',
    layout: 'left',
    bgPresetId: 'xhs-detail-lavender',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 32,
    keywordsFontSize: 13,
    defaultTitle: '自媒体人\n最需要做的事',
    defaultKeywords: '多多阅读 保持写作',
  },
  {
    id: 'xhs-canva-memphis',
    label: '孟菲斯春招',
    desc: '描边大字 · STEP 步骤体',
    group: 'xhs',
    layoutPreset: 'xhs-detail-memphis',
    fontFamily: FONT.notoSans,
    titleColor: '#1a1a1a',
    keywordsColor: '#1a1a1a',
    layout: 'left',
    bgPresetId: 'xhs-detail-memphis-cream',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 30,
    keywordsFontSize: 13,
    defaultTitle: '春招备战\n主动出击四步走！',
    defaultKeywords: 'STEP1 明确目标方向',
  },
  {
    id: 'xhs-canva-scrapbook',
    label: '手账护肤',
    desc: '薄荷框 · 网格手账体',
    group: 'xhs',
    layoutPreset: 'xhs-detail-scrapbook',
    fontFamily: FONT.wenkai,
    titleColor: '#166534',
    keywordsColor: '#166534',
    layout: 'left',
    bgPresetId: 'xhs-detail-mint-frame',
    overlayOpacity: 0,
    aspect: 'portrait',
    titleFontSize: 32,
    keywordsFontSize: 12,
    defaultTitle: '春季护肤\n小常识',
    defaultKeywords: '内外兼顾注意饮食',
  },
  {
    id: 'xhs-hit-title',
    label: '爆款大字',
    desc: '左上白字 · 竖版种草首图',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#fff1f2',
    layout: 'left',
    bgPresetId: 'xhs-coral',
    overlayOpacity: 0.1,
    aspect: 'portrait',
  },
  {
    id: 'xhs-cream-note',
    label: '奶油笔记',
    desc: '左上深字 · 干货清单风',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'left',
    bgPresetId: 'xhs-cream',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-coral-sweet',
    label: '甜系种草',
    desc: '居中 · 珊瑚粉氛围',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ffe4e6',
    layout: 'center',
    bgPresetId: 'xhs-coral',
    overlayOpacity: 0.14,
    aspect: 'portrait',
  },
  {
    id: 'xhs-macaron-diary',
    label: '手账日记',
    desc: '左上 · 马卡龙拼色',
    group: 'xhs',
    fontFamily: FONT.wenkai,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'left',
    bgPresetId: 'xhs-macaron',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-lavender-mood',
    label: '莫兰迪紫',
    desc: '居中 · 氛围感封面',
    group: 'xhs',
    fontFamily: FONT.notoSerif,
    titleColor: '#ffffff',
    keywordsColor: '#f3e8ff',
    layout: 'center',
    bgPresetId: 'xhs-lavender',
    overlayOpacity: 0.18,
    aspect: 'portrait',
  },
  {
    id: 'xhs-mint-life',
    label: '清新日常',
    desc: '左上 · 生活方式',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ecfdf5',
    layout: 'left',
    bgPresetId: 'xhs-mint',
    overlayOpacity: 0.16,
    aspect: 'portrait',
  },
  {
    id: 'xhs-warm-dry',
    label: '暖橙干货',
    desc: '左上 · 教程攻略风',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ffedd5',
    layout: 'left',
    bgPresetId: 'xhs-sunset',
    overlayOpacity: 0.12,
    aspect: 'portrait',
  },
  {
    id: 'xhs-serif-edit',
    label: '杂志编辑',
    desc: '居中 · 宋体高级感',
    group: 'xhs',
    fontFamily: FONT.notoSerif,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'center',
    bgPresetId: 'xhs-cream',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-film-vintage',
    label: '复古胶片',
    desc: '居中 · 怀旧棕调氛围',
    group: 'xhs',
    fontFamily: FONT.notoSerif,
    titleColor: '#fef3c7',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'xhs-film',
    overlayOpacity: 0.22,
    aspect: 'portrait',
  },
  {
    id: 'xhs-food-bite',
    label: '美食探店',
    desc: '左上 · 暖棕食欲感',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#fed7aa',
    layout: 'left',
    bgPresetId: 'xhs-chocolate',
    overlayOpacity: 0.14,
    aspect: 'portrait',
  },
  {
    id: 'xhs-fashion-bw',
    label: '穿搭大片',
    desc: '左上 · 黑白极简高级',
    group: 'xhs',
    fontFamily: FONT.sans,
    titleColor: '#ffffff',
    keywordsColor: '#e5e7eb',
    layout: 'left',
    bgPresetId: 'xhs-bw-soft',
    overlayOpacity: 0.1,
    aspect: 'portrait',
  },
  {
    id: 'xhs-travel-sky',
    label: '旅行打卡',
    desc: '居中 · 晴空蓝度假感',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#e0f2fe',
    layout: 'center',
    bgPresetId: 'xhs-sky',
    overlayOpacity: 0.12,
    aspect: 'portrait',
  },
  {
    id: 'xhs-neon-pop',
    label: '霓虹撞色',
    desc: '居中 · 潮流视觉冲击',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#22d3ee',
    layout: 'center',
    bgPresetId: 'xhs-neon',
    overlayOpacity: 0.08,
    aspect: 'portrait',
  },
  {
    id: 'xhs-minimal-white',
    label: '极简留白',
    desc: '居中深字 · 奶油底干净',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'center',
    bgPresetId: 'xhs-cream',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-handwrite',
    label: '手写笔记',
    desc: '左上 · 拿铁手账风',
    group: 'xhs',
    fontFamily: FONT.wenkai,
    titleColor: '#451a03',
    keywordsColor: '#78350f',
    layout: 'left',
    bgPresetId: 'xhs-latte',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-plog-daily',
    label: '日常 Plog',
    desc: '左上 · 蜜桃粉生活感',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'left',
    bgPresetId: 'xhs-peach',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-bold-hit',
    label: '大色块爆款',
    desc: '左上白字 · 强对比吸睛',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#fff1f2',
    layout: 'left',
    bgPresetId: 'xhs-coral',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-matcha-calm',
    label: '抹茶治愈',
    desc: '居中 · 清新绿意',
    group: 'xhs',
    fontFamily: FONT.notoSerif,
    titleColor: '#ffffff',
    keywordsColor: '#ecfccb',
    layout: 'center',
    bgPresetId: 'xhs-matcha',
    overlayOpacity: 0.16,
    aspect: 'portrait',
  },
  {
    id: 'xhs-ocean-trip',
    label: '海盐度假',
    desc: '居中 · 蓝海旅行风',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#bae6fd',
    layout: 'center',
    bgPresetId: 'xhs-ocean',
    overlayOpacity: 0.14,
    aspect: 'portrait',
  },
  {
    id: 'xhs-berry-mood',
    label: '浆果甜感',
    desc: '居中 · 紫色氛围感',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#f3e8ff',
    layout: 'center',
    bgPresetId: 'xhs-berry',
    overlayOpacity: 0.12,
    aspect: 'portrait',
  },
  {
    id: 'xhs-lemon-boost',
    label: '柠檬元气',
    desc: '左上深字 · 高能量吸睛',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'left',
    bgPresetId: 'xhs-lemon',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'xhs-tutorial-pro',
    label: '干货教程',
    desc: '左上 · 靛蓝专业感',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#e0e7ff',
    layout: 'left',
    bgPresetId: 'xhs-indigo',
    overlayOpacity: 0.1,
    aspect: 'portrait',
  },
  {
    id: 'xhs-beauty-rose',
    label: '美妆护肤',
    desc: '居中 · 玫瑰粉柔光',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#fce7f3',
    layout: 'center',
    bgPresetId: 'xhs-rose',
    overlayOpacity: 0.1,
    aspect: 'portrait',
  },
  {
    id: 'xhs-wenkai-literary',
    label: '文艺诗集',
    desc: '居中 · 霞鹜淡紫',
    group: 'xhs',
    fontFamily: FONT.wenkai,
    titleColor: '#ffffff',
    keywordsColor: '#f3e8ff',
    layout: 'center',
    bgPresetId: 'xhs-lavender',
    overlayOpacity: 0.2,
    aspect: 'portrait',
  },
  {
    id: 'xhs-brush-art',
    label: '毛笔艺展',
    desc: '居中 · 墨韵复古',
    group: 'xhs',
    fontFamily: FONT.mashan,
    titleColor: '#fef3c7',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'xhs-film',
    overlayOpacity: 0.28,
    aspect: 'portrait',
  },
  {
    id: 'xhs-sport-energy',
    label: '运动活力',
    desc: '左上 · 暖橙健身风',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ffedd5',
    layout: 'left',
    bgPresetId: 'xhs-sunset',
    overlayOpacity: 0.08,
    aspect: 'portrait',
  },
  {
    id: 'xhs-checklist',
    label: '清单打卡',
    desc: '左上 · 马卡龙清单体',
    group: 'xhs',
    fontFamily: FONT.notoSans,
    titleColor: XHS_INK,
    keywordsColor: XHS_INK_SOFT,
    layout: 'left',
    bgPresetId: 'xhs-macaron',
    overlayOpacity: 0,
    aspect: 'portrait',
  },
  {
    id: 'wechat-classic',
    label: '经典横封',
    desc: '居中白字 · 2.35:1 标准',
    group: 'wechat',
    fontFamily: FONT.sans,
    titleColor: '#ffffff',
    keywordsColor: '#ecfdf5',
    layout: 'center',
    bgPresetId: 'wechat-green',
    overlayOpacity: 0.12,
    aspect: 'wechat',
  },
  {
    id: 'wechat-news',
    label: '资讯左对齐',
    desc: '左上 · 灰蓝专业感',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#e2e8f0',
    layout: 'left',
    bgPresetId: 'wechat-slate',
    overlayOpacity: 0.1,
    aspect: 'wechat',
  },
  {
    id: 'wechat-cinnabar-head',
    label: '头条朱砂',
    desc: '左上 · 热点深度文',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#fef3c7',
    layout: 'left',
    bgPresetId: 'wechat-cinnabar',
    overlayOpacity: 0.14,
    aspect: 'wechat',
  },
  {
    id: 'wechat-tech',
    label: '科技深空',
    desc: '左上 · 技术教程',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#cbd5e1',
    layout: 'left',
    bgPresetId: 'ink-night',
    overlayOpacity: 0.18,
    aspect: 'wechat',
  },
  {
    id: 'wechat-paper',
    label: '人文纸感',
    desc: '左上深字 · 文化随笔',
    group: 'wechat',
    fontFamily: FONT.notoSerif,
    titleColor: '#292524',
    keywordsColor: '#57534e',
    layout: 'left',
    bgPresetId: 'paper-warm',
    overlayOpacity: 0,
    aspect: 'wechat',
  },
  {
    id: 'wechat-minimal',
    label: '极简素雅',
    desc: '居中 · 浅色底深字',
    group: 'wechat',
    fontFamily: FONT.notoSans,
    titleColor: '#1e293b',
    keywordsColor: '#64748b',
    layout: 'center',
    bgPresetId: 'wechat-soft',
    overlayOpacity: 0,
    aspect: 'wechat',
  },
  {
    id: 'wechat-jade',
    label: '青玉国风',
    desc: '居中 · 传统文化',
    group: 'wechat',
    fontFamily: FONT.wenkai,
    titleColor: '#fef9c3',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'wechat-jade',
    overlayOpacity: 0.2,
    aspect: 'wechat',
  },
  {
    id: 'wechat-brush',
    label: '墨韵毛笔',
    desc: '居中 · 诗词散文',
    group: 'wechat',
    fontFamily: FONT.mashan,
    titleColor: '#fef3c7',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'wechat-ink',
    overlayOpacity: 0.22,
    aspect: 'wechat',
  },
  {
    id: 'wechat-misty',
    label: '雾蓝商务',
    desc: '左上 · 品牌专栏',
    group: 'wechat',
    fontFamily: FONT.sans,
    titleColor: '#ffffff',
    keywordsColor: '#f0f9ff',
    layout: 'left',
    bgPresetId: 'misty-blue',
    overlayOpacity: 0.12,
    aspect: 'wechat',
  },
  {
    id: 'wechat-forest',
    label: '森系自然',
    desc: '居中 · 环保健康',
    group: 'wechat',
    fontFamily: FONT.notoSerif,
    titleColor: '#ffffff',
    keywordsColor: '#d1fae5',
    layout: 'center',
    bgPresetId: 'forest-mist',
    overlayOpacity: 0.2,
    aspect: 'wechat',
  },
  {
    id: 'tech-dark',
    label: '科技深蓝',
    desc: '居中白字 · 适合技术分享',
    group: 'business',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#e2e8f0',
    layout: 'center',
    bgPresetId: 'ink-night',
    overlayOpacity: 0.2,
  },
  {
    id: 'misty-pro',
    label: '雾蓝商务',
    desc: '左上排版 · 清爽专业',
    group: 'business',
    fontFamily: FONT.sans,
    titleColor: '#ffffff',
    keywordsColor: '#f0f9ff',
    layout: 'left',
    bgPresetId: 'misty-blue',
    overlayOpacity: 0.15,
  },
  {
    id: 'forest-calm',
    label: '森系沉稳',
    desc: '居中 · 自然绿调',
    group: 'business',
    fontFamily: FONT.notoSerif,
    titleColor: '#ffffff',
    keywordsColor: '#d1fae5',
    layout: 'center',
    bgPresetId: 'forest-mist',
    overlayOpacity: 0.25,
  },
  {
    id: 'sunrise-warm',
    label: '晨光暖调',
    desc: '居中 · 生活随笔',
    group: 'literary',
    fontFamily: FONT.wenkai,
    titleColor: '#ffffff',
    keywordsColor: '#fff7ed',
    layout: 'center',
    bgPresetId: 'sunrise-glow',
    overlayOpacity: 0.18,
  },
  {
    id: 'paper-editorial',
    label: '纸感杂志',
    desc: '左上 · 深色字纸面',
    group: 'literary',
    fontFamily: FONT.notoSerif,
    titleColor: '#292524',
    keywordsColor: '#57534e',
    layout: 'left',
    bgPresetId: 'paper-warm',
    overlayOpacity: 0,
  },
  {
    id: 'ink-brush',
    label: '墨韵国风',
    desc: '居中毛笔 · 诗意封面',
    group: 'creative',
    fontFamily: FONT.mashan,
    titleColor: '#fef3c7',
    keywordsColor: '#fde68a',
    layout: 'center',
    bgPresetId: 'ink-night',
    overlayOpacity: 0.35,
  },
  {
    id: 'forest-poetry',
    label: '林间诗意',
    desc: '居中霞鹜 · 自然文艺',
    group: 'creative',
    fontFamily: FONT.wenkai,
    titleColor: '#ffffff',
    keywordsColor: '#ecfdf5',
    layout: 'center',
    bgPresetId: 'forest-mist',
    overlayOpacity: 0.3,
  },
  {
    id: 'sunrise-bold',
    label: '暖橙大字',
    desc: '左上 · 醒目标题',
    group: 'creative',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#ffedd5',
    layout: 'left',
    bgPresetId: 'sunrise-glow',
    overlayOpacity: 0.22,
  },
  {
    id: 'minimal-paper',
    label: '极简留白',
    desc: '居中 · 纸面轻字',
    group: 'minimal',
    fontFamily: FONT.sans,
    titleColor: '#44403c',
    keywordsColor: '#78716c',
    layout: 'center',
    bgPresetId: 'paper-warm',
    overlayOpacity: 0,
  },
  {
    id: 'minimal-blue',
    label: '雾蓝轻简',
    desc: '居中 · 低遮罩清爽',
    group: 'minimal',
    fontFamily: FONT.notoSans,
    titleColor: '#ffffff',
    keywordsColor: '#f8fafc',
    layout: 'center',
    bgPresetId: 'misty-blue',
    overlayOpacity: 0.08,
  },
]

/** 小红书模板子分类（对齐 Canva 分类浏览） */
export const COVER_TEMPLATE_SUBGROUPS: Record<string, string> = {
  'xhs-canva-spring': 'Canva精选封面',
  'xhs-canva-notebook': 'Canva精选封面',
  'xhs-canva-browser': 'Canva精选封面',
  'xhs-canva-palm': 'Canva精选封面',
  'xhs-canva-workplace': 'Canva详情内页',
  'xhs-canva-media': 'Canva详情内页',
  'xhs-canva-memphis': 'Canva详情内页',
  'xhs-canva-scrapbook': 'Canva详情内页',
  'xhs-hit-title': '种草爆款',
  'xhs-bold-hit': '种草爆款',
  'xhs-coral-sweet': '种草爆款',
  'xhs-warm-dry': '种草爆款',
  'xhs-lemon-boost': '种草爆款',
  'xhs-cream-note': '奶油手账',
  'xhs-macaron-diary': '奶油手账',
  'xhs-handwrite': '奶油手账',
  'xhs-checklist': '奶油手账',
  'xhs-plog-daily': '奶油手账',
  'xhs-minimal-white': '奶油手账',
  'xhs-film-vintage': '氛围质感',
  'xhs-lavender-mood': '氛围质感',
  'xhs-berry-mood': '氛围质感',
  'xhs-neon-pop': '氛围质感',
  'xhs-serif-edit': '氛围质感',
  'xhs-wenkai-literary': '氛围质感',
  'xhs-brush-art': '氛围质感',
  'xhs-mint-life': '清新日常',
  'xhs-matcha-calm': '清新日常',
  'xhs-ocean-trip': '清新日常',
  'xhs-travel-sky': '清新日常',
  'xhs-sport-energy': '清新日常',
  'xhs-food-bite': '垂类专题',
  'xhs-fashion-bw': '垂类专题',
  'xhs-beauty-rose': '垂类专题',
  'xhs-tutorial-pro': '垂类专题',
}

export const XHS_SUBGROUP_ORDER = [
  'Canva精选封面',
  'Canva详情内页',
  '种草爆款',
  '奶油手账',
  '氛围质感',
  '清新日常',
  '垂类专题',
] as const

export function getCoverTemplateSubgroup(id: string): string | undefined {
  return COVER_TEMPLATE_SUBGROUPS[id]
}

export function getCoverTemplateAspect(template: CoverTemplate): CoverAspect {
  return template.aspect ?? 'landscape'
}

export function filterCoverTemplatesByAspect(
  templates: CoverTemplate[],
  aspect: CoverAspect,
): CoverTemplate[] {
  return templates.filter((t) => getCoverTemplateAspect(t) === aspect)
}

export function getCoverTemplate(id: string): CoverTemplate | undefined {
  return COVER_TEMPLATES.find((t) => t.id === id)
}

export function coverTemplateStyleFields(template: CoverTemplate) {
  const fields: Partial<CoverEditorState> = {
    fontFamily: template.fontFamily,
    titleColor: template.titleColor,
    keywordsColor: template.keywordsColor,
    layout: template.layout,
    bgPresetId: template.bgPresetId,
    overlayOpacity: template.overlayOpacity,
    layoutPreset: template.layoutPreset ?? 'default',
  }
  if (template.titleFontSize != null) fields.titleFontSize = template.titleFontSize
  if (template.keywordsFontSize != null) fields.keywordsFontSize = template.keywordsFontSize
  return fields
}
